### ISSUE TITLE
Implementation of Plant rarity possibilities

### ISSUE THREAD

**Issue by MrEMU** [Stefuniverse/Midgard-Electron#6]
Plant rarities should have following possibilities:
1: 90%    2: 9%    3: 1%

**Comment by Stefuniverse** [comment]
Implementation: 
1. Select rarity class
2. Select plant from rarity class
3. If no plant in this rarity class is available, the algoritthm will reroll.

**Comment by Stefuniverse** [comment]
implemented in f1a3cc14f06e240366abe5d8c9134257783f75b1
