### ISSUE TITLE
Sanitize Area Country combinatios

### ISSUE THREAD

**Issue by Stefuniverse** [Stefuniverse/Midgard-Electron#8]
e.g. in desserts in Alba it is opossible to find insects. However Alba obviously has no desserts. Therefore we should change the data structure like this : countries : { Alba : ["forest" , "city", ..], Escher : ["dessert"]}

Makes it also possible to add several special creatures in special places,

**Comment by MrEMU** [comment]
Finished and tested a script to convert the old format in this new one.

**Comment by Stefuniverse** [comment]
new format implemented with de91437dd1430a90ea871bfc3ead4320d32aebb5
