### ISSUE TITLE
Improvement of Rarity through possibilities and colors

### ISSUE THREAD

**Issue by MrEMU** [Stefuniverse/Midgard-Electron#9]
Implement the rarity of beasts with the belonging colors:

![](https://i.imgur.com/1A6DxL5.png)

Add the colors for the plants rarity:

![](https://i.imgur.com/1dO2Br1.png)

**Comment by Stefuniverse** [comment]
Implemented with f4b0a4a6d2a3f3709b42fc9a7de502d260d57c4d
